Map<String, String> arLang = {
  "invoice_amount": "مبلغ الفاتورة",
  "currency_unit": "الوحدة المالية",
  "promotion_groups": "مجموعات العروض الترويجية",
  "payment_method": "طريقة الدفع",
  "store": "المخزن",
  "store_groups": "مجموعات المخازن",
  "store_region_number": "رقم المنطقة المخزن",
  "customer_type": "نوع العميل",
  "customer_group": "مجموعة العملاء",
  "customer_degree": "درجة العميل",
  "customer_activity": "نشاط العميل",
  "customer_classification": "تصنيف العميل",
  "customer_number": "رقم العميل",
  "my_customers": "عملاء نقاطي",
  "available_data": "البيانات المتاحة",
  "selected_data": "البيانات المختارة",
  "exit": "خروج",
  "execute": "تنفيذ",
  "delete_all": "حذف الكل",
  "search_in_detailed_data": "بحث في البيانات التفصيلية",
  "add_all": "إضافة الكل",
};
