import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

const transparent = Colors.transparent;
const whiteColor = Color(0xFFFFFFFF);
const kPrimaryColor = Color(0xFF094F90);
const kTopAppBar = Color(0xFF04386A);
const kDarkPrimaryColor = Color(0xFF004F62);
const kColapsColor = Color(0xFFF9F9F9);
const kButtonDashBoard = Color(0xFFF45E5E);
const primaryColor = Color(0xFF2697FF);
const actionHoverLinksBG = Color(0xFFEBF9FF);
const secondaryColor = Color(0xFF2A2D3E);
const shadowColor = Color(0xFF9E9E9E);
const ccColor = Color(0xFFCCCCCC);
const cTABGSuccessColor = Color(0xFFF1FEF0);
const Color kTextColor = Color(0xFF474747);
const Color kCardGreenColor = Color(0xFF319626);
const Color dividerColor = Color(0xFFE2E2E2);
const Color kTextFieldColor = Color(0xFF808080);
const Color kOffColor = Color(0x0ff1f5fb);
const kBackgroundCardColor = Color(0xFFF4F4F4);
const kSkyDarkColor = Color(0xFF0C69C0);
const kStrockColor = Color(0xFFD2ECFC);
const kTextFiledColor = Color(0xFF819AA7);
const notActiveColor = Color(0xFFF1F9FF);
const actionColors = Color(0xFF00B4D8);
const disabledColor = Color(0xFF8A8A8A);
const descriptionColor = Color(0xFF4B4B4B);
const dotColor = Color(0xFFD9D9D9);
const gray100Text = Color(0xFFB7BABF);
const kGrayIX = Color(0xFFF2F2F2);
const kSkyButton = Color(0xFF609FFF);
const kSky2Button = Color(0xFFF2F8FF);
const kButtonRedDark = Color(0xFFD42A0F);
const Color kHomeColor = Color(0xFFF8FCFF);
const Color kBlackText = Color(0xFF000000);
const kWhiteCardColor = Color(0xFFF5F5F5);
const paymentbgColor = Color(0xFFEBF8FF);
const orderTableBg = Color(0xFFF6F6F6);
const landingTextFieldBg = Color(0xFFF2F7FC);
const labelColor =  Color(0xFF7E7E7E);
const homeButtonColor = Color(0xFF319626);
const homeIconColor=Color(0xFFC6C6C6);

const popOverColor= Color.fromARGB(
                                                255, 232, 251, 254);
